name: Feature Proposal 🚀
description: Submit a proposal for a new feature
title: '[Feature]: '
labels: [':rocket: Feature Request']
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for taking the time to suggest a new feature!
  - type: textarea
    id: description
    attributes:
      label: '🚀 Feature Proposal'
      description: A clear and concise description of what the feature is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Motivation
      description: Outline your motivation for the proposal. How will it make the boilerplate better?
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Example
      description: Describe how this feature would be used.
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Pitch
      description: Why does this feature belong in the boilerplate? 
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Common proposals that do not typically make it into the boilerplate:
          
        - Experimental features
        - Uncommon features/settings for Electron apps development
