name: Node CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - 'release/**'
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  prepare-npm-cache-ubuntu:
    uses: ./.github/workflows/prepare-cache.yml
    with:
      os: ubuntu-latest
  prepare-npm-cache-macos:
    uses: ./.github/workflows/prepare-cache.yml
    with:
      os: macos-latest
  prepare-npm-cache-windows:
    uses: ./.github/workflows/prepare-cache.yml
    with:
      os: windows-latest

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: prepare-npm-cache-ubuntu

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - name: install
        run: npm ci
      - name: run eslint
        run: npm run lint

  test-ubuntu:
    uses: ./.github/workflows/test.yml
    needs: prepare-npm-cache-ubuntu
    with:
      os: ubuntu-latest
  test-macos:
    uses: ./.github/workflows/test.yml
    needs: prepare-npm-cache-macos
    with:
      os: macos-latest
  test-windows:
    uses: ./.github/workflows/test.yml
    needs: prepare-npm-cache-windows
    with:
      os: windows-latest

  bundle-linux:
    uses: ./.github/workflows/webpack.yml
    needs: test-ubuntu
    with:
      os: ubuntu-latest
  bundle-mac:
    uses: ./.github/workflows/webpack.yml
    needs: test-macos
    with:
      os: macos-latest
  bundle-windows:
    uses: ./.github/workflows/webpack.yml
    needs: test-windows
    with:
      os: windows-latest

  build-mac:
    uses: ./.github/workflows/build.yml
    needs: bundle-mac
    with:
      os: macos-latest
      test-only: true
  build-windows:
    uses: ./.github/workflows/build.yml
    needs: bundle-windows
    with:
      os: windows-latest
      test-only: true
