name: Prepare CI cache

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  prepare-npm-cache:
    name: Prepare npm cache for ${{ input.os }}
    runs-on: ${{ input.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm

      - name: Validate cache
        run: npm ci --omit optional
