name: Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x]
    name: Node v${{ matrix.node-version }} on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install
        run: npm ci --omit optional
      - name: Run tests
        run: npm run jest-ci
